/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package t3;

    import java.util.List;
    import javax.swing.DefaultListModel;

    import java.util.ArrayList;
/**
 *
 * @author Leonardo
 */
public class JFrameGestionCatalogo extends javax.swing.JFrame {

    private List<RopaVaron> varones;
    private List<RopaDama> damas;
    private List<RopaNiño> niños;
    
        private DefaultListModel<String> modelo;
    /**
     * Creates new form JFrameGestionCatalogo
     */
    public JFrameGestionCatalogo() {
        initComponents();
        varones = new ArrayList<>(); 
        damas=new ArrayList<>(); 
        niños =new ArrayList<>(); 
        modelo = new DefaultListModel<>();
        lstCat.setModel(modelo);
        this.setLocationRelativeTo(null);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCat = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        btnRopaVaron = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnRopaDamas = new javax.swing.JButton();
        btnopaNiños = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        lstCat.setBackground(new java.awt.Color(255, 255, 255));
        lstCat.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(lstCat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 750, 260));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/T3Recursos/Group 7.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        btnRopaVaron.setIcon(new javax.swing.ImageIcon(getClass().getResource("/T3Recursos/Group 3 (3).png"))); // NOI18N
        btnRopaVaron.setBorder(null);
        btnRopaVaron.setContentAreaFilled(false);
        btnRopaVaron.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRopaVaronActionPerformed(evt);
            }
        });
        jPanel1.add(btnRopaVaron, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/T3Recursos/Group 6 (2).png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        btnRopaDamas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/T3Recursos/Group 4 (2).png"))); // NOI18N
        btnRopaDamas.setBorder(null);
        btnRopaDamas.setContentAreaFilled(false);
        btnRopaDamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRopaDamasActionPerformed(evt);
            }
        });
        jPanel1.add(btnRopaDamas, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, -1, -1));

        btnopaNiños.setIcon(new javax.swing.ImageIcon(getClass().getResource("/T3Recursos/Group 5 (2).png"))); // NOI18N
        btnopaNiños.setBorder(null);
        btnopaNiños.setContentAreaFilled(false);
        btnopaNiños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopaNiñosActionPerformed(evt);
            }
        });
        jPanel1.add(btnopaNiños, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/T3Recursos/Rectangle 1 (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRopaVaronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRopaVaronActionPerformed
        // TODO add your handling code here:
        JFrameCatVaron IrVaron = new JFrameCatVaron(this);
        IrVaron.setLocationRelativeTo(this);
        IrVaron.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRopaVaronActionPerformed

    private void btnRopaDamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRopaDamasActionPerformed
        // TODO add your handling code here:
        JFrameCatDama IrDama = new JFrameCatDama(this);
        IrDama.setLocationRelativeTo(this);
        IrDama.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRopaDamasActionPerformed

    private void btnopaNiñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopaNiñosActionPerformed
        // TODO add your handling code here:
        JFrameCatNiños IrNiño = new JFrameCatNiños(this);
        IrNiño.setLocationRelativeTo(this);
        IrNiño.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnopaNiñosActionPerformed

    
    
     //----------------------------------------------------------------------------------------------------------------------------------------------------------
     public void agregarNewVaron(RopaVaron varon){
        varones.add(varon);
        modelo.addElement(varon.GetTexto());
    }
      //----------------------------------------------------------------------------------------------------------------------------------------------------------
       public void agregarNewDama(RopaDama dama){
        damas.add(dama);
         modelo.addElement(dama.GetTexto());
    }
        //----------------------------------------------------------------------------------------------------------------------------------------------------------
         public void agregarNewNiño(RopaNiño niño){
        niños.add(niño);
        modelo.addElement(niño.GetTexto());
    }
      //----------------------------------------------------------------------------------------------------------------------------------------------------------
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameGestionCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameGestionCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameGestionCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameGestionCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameGestionCatalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRopaDamas;
    private javax.swing.JButton btnRopaVaron;
    private javax.swing.JButton btnopaNiños;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstCat;
    // End of variables declaration//GEN-END:variables
}
